apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/traefik.yaml
  - sources/nextcloud.yaml
  - sources/postgresql-chart.yaml
  - storageclass/local-storage.yaml
  - traefik/namespace.yaml
  - traefik/helmrelease.yaml