apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/rykhalskyi/homelab-nginx:sha-e44f6a9b88342edf258015c7f4f8039045a2329a@sha256:b142bf45d1fb919ecc9bf32bcdcbdca82789884f1e31b187488eb63b557a7b2a
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi