apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/rykhalskyi/homelab-nginx:sha-a92e248639ef4cb4e3b70962d31cd933aabba498@sha256:e04cd2144094155feb2e8c49d86b9d27b55c3ab276c265c35319ae4796898be8
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi